# Generated by Django 4.2.7 on 2023-11-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="eventregistration",
            name="eid",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="eventregistration",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
